name: Release .exe

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Start web server
      run: |
        nohup dotnet run --project src/Chirp.Razor/Chirp.Razor.csproj --urls "http://127.0.0.1:5273" > server.log 2>&1 &
        sleep 2
        cat server.log
    - name: Wait for server up
      run: |
        for i in {1..180}; do
          echo "Waiting for server..."
          if curl --fail http://127.0.0.1:5273 > /dev/null 2>&1; then
            echo "Server is UP"
            exit 0
          fi
          sleep 1
          cat server.log || true
        done
        echo "Server failed to start"
        exit 1

  publish:
    
    needs: build
    runs-on: ubuntu-latest

    if: ${{ needs.build.result == 'success' }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Publish for Windows
        run: dotnet publish src/Chirp.Razor/Chirp.Razor.csproj -c Release -r win-x64 --self-contained false -p:PublishSingleFile=true -o publish/win-x64
      - name: Publish for macOS
        run: dotnet publish src/Chirp.Razor/Chirp.Razor.csproj -c Release -r osx-x64 --self-contained false -p:PublishSingleFile=true -o publish/osx-x64
      - name: Publish for Linux
        run: dotnet publish src/Chirp.Razor/Chirp.Razor.csproj -c Release -r linux-x64 --self-contained false -p:PublishSingleFile=true -o publish/linux-x64
      
      - name: Create Windows zip
        run: |
          cd publish/win-x64
          zip -r ../../chirp-windows-x64.zip .

      - name: Create macOS zip
        run: |
          cd publish/osx-x64
          zip -r ../../chirp-macos-x64.zip .

      - name: Create Linux zip
        run: |
          cd publish/linux-x64
          zip -r ../../chirp-linux-x64.zip .

      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            chirp-windows-x64.zip
            chirp-macos-x64.zip
            chirp-linux-x64.zip
          generate_release_notes: true